### ISSUE TITLE
Bug: Source parameter of type 'javax.xml.transform.stax.StAXSource' is not accepted by this validator.

### ISSUE THREAD

**Issue by volkerkochnovatec** [NovaTecConsulting/stereotype-check#53]
Using Maven to execute the stereotyp checker produces the following exception

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.10:check (checkstyle) on project jobservice: Failed during checkstyle configuration: cannot initialize module TreeWalker - Source parameter of type 'javax.xml.transform.stax.StAXSource' is not accepted by this validator.
Caused by: java.lang.IllegalArgumentException: Source parameter of type 'javax.xml.transform.stax.StAXSource' is not accepted by this validator.
	at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at info.novatec.ita.check.config.StereotypeCheckReader.read(StereotypeCheckReader.java:405)
	at info.novatec.ita.check.config.StereotypeCheckReader.read(StereotypeCheckReader.java:437)
	at info.novatec.ita.check.StereotypeCheck.init(StereotypeCheck.java:90)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:185)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:174)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:162)
```

**Comment by volkerkochnovatec** [comment]
The  cause is that maven uses a different implementation of jaxp
org.apache.xerces.jaxp
The validtorImpl cannot handle a StaxSource
the default which is provided by the JDK is
com.sun.org.apache.xerces.internal.jaxp
This Implementation can handle StaxSource.
